Улучшения в сборке образа

diff --git a/go/1598560/Dockerfile b/go/1598560/Dockerfile
--- a/go/1598560/Dockerfile
+++ b/go/1598560/Dockerfile
@@ -1,7 +1,10 @@
 FROM golang:alpine
 
+ARG UID
+
 RUN apk add make gcc
 RUN apk add musl-dev
-# RUN apk add bash
 RUN apk add sed
-RUN adduser -D user
+
+RUN test -z "${UID}" && { echo 'Missing UID build parameter'; exit 1; } || true
+RUN adduser -D -u ${UID} user
